### ISSUE TITLE
ee.data.getTaskStatus returns nothing if the task has state='FAILED'

### ISSUE THREAD

**Issue by DaveA-W** [google/earthengine-api#108]
Given the ID of a failed task seen within ee.data.getTaskList(), 
ee.data.getTaskStatus(failedTaskId) returns no details via the Javascript API v0.1.202

Playground script demonstrating the issue at https://code.earthengine.google.com/7840ac249bf4004ad84625602774608d

This issue seems to be present in both the legacy and v1alpha (setCloudApiEnabled(true)) platforms.

**Comment by tylere** [comment]
Thanks for the bug report!

We have been transitioning to using Google Issue Tracker for Earth Engine [bug reports](https://issuetracker.google.com/issues?q=componentid:184406%20type:bug) and [feature requests](https://issuetracker.google.com/issues?q=componentid:184406%20type:feature_request) in order to better integrate with the Earth Engine team's workflow.

I am marking this bug report as closed, but feel free to open a new issue according to instructions on the Earth Engine doc's [Get Help](https://developers.google.com/earth-engine/help) page.
