### ISSUE TITLE
ee.data.startProcessing and startIngestion start tasks with ids that don't match their taskId input parameter

### ISSUE THREAD

**Issue by DaveA-W** [google/earthengine-api#110]
The javascript v0.1.201 implementation of `ee.data.newTaskId()` generates guids when the cloud api is enabled.  Supplying one of these to `ee.data.startProcessing` or `ee.data.startIngestion` results in a task with non-guid IDs.  The `startProcessing` callback is supplied with a payload that at least informs the caller of the new taskId - but `startIngestion` does not.

So if we want to start an ingestion task, the only way to identify which one was started is to trawl ee.data.getTaskList() for a matching description.

Example showing how `startProcessing` modifies the task ID is shown at https://code.earthengine.google.com/7840ac249bf4004ad84625602774608d

**Comment by DaveA-W** [comment]
Note: both `startProcessing` and `startIngestion` used to honor the incoming taskId parameter - newly started tasks would keep that value as their task IDs.

**Comment by tylere** [comment]
Thanks for the bug report!

We have been transitioning to using Google Issue Tracker for Earth Engine [bug reports](https://issuetracker.google.com/issues?q=componentid:184406%20type:bug) and [feature requests](https://issuetracker.google.com/issues?q=componentid:184406%20type:feature_request) in order to better integrate with the Earth Engine team's workflow.

I am marking this bug report as closed, but feel free to open a new issue according to instructions on the Earth Engine doc's [Get Help](https://developers.google.com/earth-engine/help) page.
