### ISSUE TITLE
CORS-related issue on ee.initialize() v0.1.201 loading algorithms and other resources

### ISSUE THREAD

**Issue by DaveA-W** [google/earthengine-api#112]
The Chromium-based Brave browser available from https://brave.com includes some additional default security settings.  With these applied, EE fails to load its resources with the error:
```
  "error": {
    "code": 400,
    "message": "Bad request: Origin and Referer header don't match. Origin: https://code.earthengine.google.com, Referer: https://content-earthengine.googleapis.com/",
    "status": "INVALID_ARGUMENT"
  }
```
This also occurs on the playground https://code.earthengine.google.com/
![image](https://user-images.githubusercontent.com/6415842/65740313-d32f4300-e11a-11e9-979d-0e715a4cc506.png)

It can be worked around by asking users to manually switch off Brave's default shields, but would be better not to have to.  Older ee_api_js scripts did not exhibit the issue.

**Comment by tylere** [comment]
Thanks for the bug report!

We have been transitioning to using Google Issue Tracker for Earth Engine [bug reports](https://issuetracker.google.com/issues?q=componentid:184406%20type:bug) and [feature requests](https://issuetracker.google.com/issues?q=componentid:184406%20type:feature_request) in order to better integrate with the Earth Engine team's workflow.

I am marking this bug report as closed, but feel free to open a new issue according to instructions on the Earth Engine doc's [Get Help](https://developers.google.com/earth-engine/help) page.
