### ISSUE TITLE
How to manage GEE assets with service account (Permission issue)

### ISSUE THREAD

**Issue by RamizSami** [google/earthengine-api#113]
I need to export some images to my GEE Assets using the Python API and I am getting this error: "Insufficient permissions to create asset 'users/ramizsami95/kyrgyz/ndvi_anomaly". This is my code:
`task = ee.batch.Export.image.toAsset(
        image=anomaly,
        description='NDVI-anomaly',
        assetId='users/ramizsami95/kyrgyz/ndvi_anomaly')`
In the Python code, I have authenticated with a service account that is created from my Gmail account and it seems like it can't access my GEE assets. Now I have two questions: 
1) Is there a way that I can give owner access to this kyrgyz folder to my service account? (I have given writer permission already). 
2) Do we have separate assets for the service account that I am missing?

**Comment by tylere** [comment]
Thanks for the bug report!

We have been transitioning to using Google Issue Tracker for Earth Engine [bug reports](https://issuetracker.google.com/issues?q=componentid:184406%20type:bug) and [feature requests](https://issuetracker.google.com/issues?q=componentid:184406%20type:feature_request) in order to better integrate with the Earth Engine team's workflow.

I am marking this bug report as closed, but feel free to open a new issue according to instructions on the Earth Engine doc's [Get Help](https://developers.google.com/earth-engine/help) page.
