### ISSUE TITLE
Javascript: ee.data.createAsset and createFolder don't accept forceOverwrite=true

### ISSUE THREAD

**Issue by DaveA-W** [google/earthengine-api#116]
Docs show both these methods should accept a `forceOverwrite` boolean parameter, but if you set this to `true` with the Javascript API v0.1.202 and `setCloudApiEnabled`, then they immediately fail with `Asset overwrite not supported`.

This is also currently the case in the playground - demo at https://code.earthengine.google.com/76283f363d0a2408a711c0a638796691

![image](https://user-images.githubusercontent.com/6415842/66484930-7d737700-eada-11e9-849e-7645e783461c.png)

**Comment by tylere** [comment]
Thanks for the bug report!

We have been transitioning to using Google Issue Tracker for Earth Engine [bug reports](https://issuetracker.google.com/issues?q=componentid:184406%20type:bug) and [feature requests](https://issuetracker.google.com/issues?q=componentid:184406%20type:feature_request) in order to better integrate with the Earth Engine team's workflow.

I am marking this bug report as closed, but feel free to open a new issue according to instructions on the Earth Engine doc's [Get Help](https://developers.google.com/earth-engine/help) page.
