### ISSUE TITLE
Javascript: ee.data.createFolder no longer works v0.1.201

### ISSUE THREAD

**Issue by DaveA-W** [google/earthengine-api#117]
With `setCloudApiEnabled(true)`, ee.data.createFolder now consistently errors with `If legacy or public asset, assetId must be present`

The issue _can_ be worked around by calling `ee.data.createAsset({type: 'Folder'})` instead with the same folder path (= asset id).

**Comment by tylere** [comment]
Thanks for the bug report!

We have been transitioning to using Google Issue Tracker for Earth Engine [bug reports](https://issuetracker.google.com/issues?q=componentid:184406%20type:bug) and [feature requests](https://issuetracker.google.com/issues?q=componentid:184406%20type:feature_request) in order to better integrate with the Earth Engine team's workflow.

I am marking this report as closed, but feel free to open a new bug according to instructions on the Earth Engine doc's [Get Help](https://developers.google.com/earth-engine/help) page.
