### ISSUE TITLE
Support Importing tf.js in Code Editor Window

### ISSUE THREAD

**Issue by ucalyptus** [google/earthengine-api#119]
I wish to request for importing tensorflow.js in the gee editor so as to be able to use these image tiles as tensor for Neural Network models directly without using GCS buckets and Python/Jupyter.

**Comment by tylere** [comment]
Thanks for the feature request!

We have been transitioning to using Google Issue Tracker for Earth Engine [bug reports](https://issuetracker.google.com/issues?q=componentid:184406%20type:bug) and [feature requests](https://issuetracker.google.com/issues?q=componentid:184406%20type:feature_request) in order to better integrate with the Earth Engine team's workflow.

I am marking this feature request as closed, but feel free to open a new bug according to instructions on the Earth Engine doc's [Get Help](https://developers.google.com/earth-engine/help) page.
