### ISSUE TITLE
AI platform unable to create model endpoint from eeified model

### ISSUE THREAD

**Issue by safgen** [google/earthengine-api#147]
The AI platform successfully creates a model  when the version is created from the model directory created during the training but it fails to create it from the 'eeified' model a described in the following notebook: python/examples/ipynb/AI_platform_demo.ipynb

ERROR: (gcloud.ai-platform.versions.create) Error: model server never became ready. Please validate that your model file or container configuration are valid

**Comment by leechengfa** [comment]
I have the same problem.

In addition, I managed to contact Google Cloud Support on this issue. They tried to troubleshoot by running/replicating this Jupyter Notebook in their environment and still received the same error. As such, their conclusion was that the error stemmed from the code itself and redirected me here. Should you require my GCS case number, I would be able to provide it privately.

**Comment by tylere** [comment]
In order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for details on how to browse and submit issues to Issue Tracker.
