### ISSUE TITLE
ee.mapclient: python3 do not support cStringIO

### ISSUE THREAD

**Issue by Brandon03** [google/earthengine-api#16]
notice "import cStringIO" at mapclient.py (line 449 & line 31), which python3 does not support, could change to  "from io import StringIO"

**Comment by defelix** [comment]
It occurred the same issue to me using python 3 and import ee.mapclient.
Any solution?

**Comment by tylere** [comment]
We have not been actively maintaining the mapclient object, because it depends on Tk, a graphical user interface toolkit, which behaves differently on different machines.

Could you describe your use case that requires mapclient? We may be able to suggest an alternative approach.

**Comment by defelix** [comment]
I installed Earth Engine on Anaconda platform and python 3.6 on windows 10 machine.
whenever I try to import mapclient object I get that error; at the end I came back to python 2.7.

**Comment by 00krishna** [comment]
Hey folks. I understand that this is marked as `wontfix` but is there some workaround for people using Python 3? The example code in the repo still references using the `ee.mapclient` instruction, so that is confusing. I provided an example of the problem below.

I am just not clear on what the alternative is to using `ee.mapclient` to plot image? Is there another map command in the python 3 api? Or do I have to just download the image and display them locally? 

https://github.com/google/earthengine-api/blob/master/python/examples/py/Image/hdr_landsat.py
```
ee.mapclient.centerMap(-95.738, 18.453, 9)
# Display the image normally.
ee.mapclient.addToMap(image, {'gain': '1.6, 1.4, 1.1'}, 'Land')
# Add and stretch the water.  Once where the elevation is masked,
# and again where the elevation is zero.
elev = ee.Image('srtm90_v4')
mask1 = elev.mask().eq(0).And(image.mask())
mask2 = elev.eq(0).And(image.mask())
ee.mapclient.addToMap(
    image.mask(mask1), {'gain': 6.0, 'bias': -200}, 'Water: Masked')
ee.mapclient.addToMap(
    image.mask(mask2), {'gain': 6.0, 'bias': -200}, 'Water: Elev 0')
```
Is there an alternative

**Comment by joshwapiano** [comment]
Hey all, any chance you've been able to import the tkinter library using python version 3?
The closest I've managed to get after hours of trying different things is:
`ImportError: No module named '_tkinter', please install the python3-tk package`
Not feeling very optimistic that I'll be able to use the Google Earth Engine Python API for my research after several days not getting very far.

**Comment by tylere** [comment]
We don't plan on putting effort into resolving the platform-specific mapclient/tkinter issues, because there are better options that work cross-platform. In particular, Jupyter Notebooks are quite handy for working with the EE Python API. See:
https://github.com/gee-community/ee-jupyter-contrib
https://github.com/tylere/agu2017

(I hope that makes you feel more optimistic.)

**Comment by joshwapiano** [comment]
Hi Tyler, thanks for the speedy response - the use of Jupyter Notebooks certainly does make me feel more optimistic. It's a shame this information isn't on the [Earth Engine python install page](https://developers.google.com/earth-engine/python_install) for others to find, perhaps in future this will be the case though? (Apologies if this is something I've missed)
I'll look in to the link you've shared - I'm having to use a Linux VM for Docker as I'm not on the latest Windows 10 which has caused me issues with ports but I'll see what I can achieve. Thanks again.

**Comment by 4al15ec022** [comment]
In mapclient , cStringIO.StringIO is used ,
So in python 3 it's io.BytesIO instead of cStringIO.StringIO
So import io and replace cStringIO.StringIO by io.BytesIO,,,, and install  python3-tk from apt ,, from apt ,,,,, replace "import Tkinter" by import tkinter as Tkinter ,,,,,, that's it works perfectly fine in python 3 environment both in windows and Linux

**Comment by ravish0007** [comment]
In mapclient , cStringIO.StringIO is used ,
So in python 3 it's io.BytesIO instead of cStringIO.StringIO
So import io and replace cStringIO.StringIO by io.BytesIO,,,, and install python3-tk from apt ,, from apt ,,,,, replace "import Tkinter" by import tkinter as Tkinter ,,,,,, that's it works perfectly fine in python 3 environment both in windows and Linux

**Comment by lieying2016** [comment]
Why does not my mapclient work in Jupyther Noterbooks? The error is "name Queue is not defined". I used 
try:
    import queue
except ImportError:
    import Queue as queue

**Comment by fitoprincipe** [comment]
Hi @lieying2016 , as you are using the Jupyter environment, have you tried [geetools](https://github.com/gee-community/gee_tools/blob/master/notebooks/map_visualization.ipynb)? Under the `develop` branch I have made many improvements, haven't merged them yet, but you can try them anyway.

**Comment by lieying2016** [comment]
Thanks @fitoprincipe . I will try.

As you mentioned geetools, I wanted to share with you an issue when I use geetools.
https://gis.stackexchange.com/questions/279412/exporting-large-number-of-landsat-images-from-google-earth-engine
I followed your answer to this issue(downloading imageCollection from GEE), but I got another problem. Here is my code:
==================================================================================
# download the data

ndvi = ee.ImageCollection('MODIS/006/MOD13A2').filterDate('2009-01-01','2017-12-31').select('NDVI')
ndvi_mon =ndvi.filter(ee.Filter.calendarRange(2009,2017,'year'))
                     .filter(ee.Filter.calendarRange(6,7,'month'))
from geetools import tools
# download  image
tasks = tools.col2drive(ndvi_mon, 'NDVI0607', scale=1000)
==================================================================================
try n° 0 ERROR: name 'TYPES' is not defined
try n° 1 ERROR: name 'TYPES' is not defined
try n° 2 ERROR: name 'TYPES' is not defined
try n° 3 ERROR: name 'TYPES' is not defined
try n° 4 ERROR: name 'TYPES' is not defined

**Comment by lieying2016** [comment]
Although I added (dataType = 'float') to col2drive, it is still the same error. @fitoprincipe

**Comment by fitoprincipe** [comment]
Ok, you should post it [here](https://github.com/gee-community/gee_tools/issues)

**Comment by maykef** [comment]
hey @fitoprincipe I'm working with geetools in jupyter, but I've got some problems with visualising Copernicus Sentinel 2 imagery. It works well with Landsat. I also noticed I cannot run ee.mapclient, it gives me this error:

`Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/maykef/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/maykef/anaconda3/lib/python3.7/site-packages/ee/mapclient.py", line 125, in run
    self.parent = Tkinter.Tk()
  File "/home/maykef/anaconda3/lib/python3.7/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable`

**Comment by fitoprincipe** [comment]
Hi @maykef ! Please post it in https://github.com/gee-community/gee_tools/issues. Thank you

**Comment by schwehr** [comment]
The EE python client is now only python >= 3.7. Closing this issue.
