### ISSUE TITLE
AttributeError: module 'ee' has no attribute 'Reducer'

### ISSUE THREAD

**Issue by wangxinzhi0617** [google/earthengine-api#164]
why?please.

**Comment by fitoprincipe** [comment]
Hi @NgoshaJr, you don't have to create new issues here, but
1. I guess you are using the Python API
2. It seems like you did not initialize EE:
```
import ee
ee.Initialize()
reducer = ee.Reducer.mean()
```
should work

**Comment by aazuspan** [comment]
Hi @fitoprincipe, initializing EE fixes the problem, but this means if you write a Python module that uses `ee.Reducer` as a type hint or default arg, it can't be imported without initializing Earth Engine first.

Say you have a module `foo` with one function `bar`:
```python
import ee

def bar(img: ee.Image, reducer: ee.Reducer=ee.Reducer.mean()):
   return img.reduce(reducer)
```

If you try to import it without initializing, an error will be thrown.
```python
>>>  from foo import bar

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/az/eexarray/eexarray/foo.py", line 3, in <module>
    def bar(img: ee.Image, reducer: ee.Reducer=ee.Reducer.mean()):
AttributeError: module 'ee' has no attribute 'Reducer'
```

If you remove ee.Reducer as a type hint and default arg, it has no problem using `ee.Image` without initializing.
```python
import ee

def foo(img: ee.Image, reducer):
   return img.reduce(reducer)
```

Maybe there's a really good reason why `ee.Reducer` (and `ee.Kernel`) can't be imported without initializing while other ee classes like `ee.Image` can be, but if not it would be awesome to have a fix since it forces some ugly workarounds for Python packages that extend Earth Engine.

**Comment by fitoprincipe** [comment]
Yes @aazuspan, I've been there and totally agree with you. We should probably discuss this in the [Developer Forum](https://groups.google.com/forum/#!forum/google-earth-engine-developers). We might catch a core dev attention.

**Comment by aazuspan** [comment]
Good idea! Just opened a topic [here](https://groups.google.com/g/google-earth-engine-developers/c/5WsB-Ui6i-s) if you want to discuss :)
