### ISSUE TITLE
Error: Server Error

### ISSUE THREAD

**Issue by lequynhhoa** [google/earthengine-api#22]
I put a service account  in config.py file and save it. Then I deployed the Server-auth (https://server-auth-dot-ee-demos.appspot.com/) but I got error:
**Error: Server Error

The server encountered an error and could not complete your request.
Please try again in 30 seconds.**

My link: http://gfd-forest.appspot.com/

Could you please tell me why?

**Comment by tylere** [comment]
Have you registered your [service account to access Earth Engine](https://developers.google.com/earth-engine/service_account#register-the-service-account-to-use-earth-engine)?

If that does not solve the issue, could you provide detailed descriptions on how you created/modified the application that is giving you the error. Also include any relevant log information.

**Comment by lequynhhoa** [comment]
I registered my service account.
I send the link detail video I deploy: https://www.screencast.com/t/NIiFFC3xyT

**Comment by tylere** [comment]
Before attempting to deploy your App Engine project to the cloud, you should first check to see that it runs successfully on the [App Engine development server](https://cloud.google.com/appengine/docs/standard/python/tools/using-local-server). Start up the development server by running to command: `dev_appserver.py .` Fix any issues before attempting to deploy the app.

From the screencast it looks like you did not create a service account credentials file named `privatekey.json` and place it in the root directory of the App Engine project, as described in the docs [Deploying App Engine apps with Earth Engine](https://developers.google.com/earth-engine/app_engine_intro#2-set-up-credentials).

**Comment by lequynhhoa** [comment]
I maked file provatekey.json and running to dev_appserver.py but I get some errors.
My processing made here: https://www.screencast.com/t/GkDlqcoipRte

Could you tell me why dev_appserver command some errors. Thank you

**Comment by tylere** [comment]
Your screencast shows a traceback error when you attempt to open the web page being served by the development server:
`ImportError: No module named ee`
I am guessing that you did not run the `build.sh` script for the project, which installs the Earth Engine Python package and its dependencies. See the following documentation: [App Engine & Earth Engine Overview: Set up the local development environment](https://developers.google.com/earth-engine/app_engine_intro#3-set-up-the-local-development-environment).

**Comment by tylere** [comment]
@lequynhhoa were you able to resolve this issue?

**Comment by lequynhhoa** [comment]
Hi Tyler,

A long time I don't study app engine. Today, I come back.
I run build.sh for the project but I get error: permission denied, Could
you tell me why?





Hoa Le

*Le Thi Quynh Hoa*

GreenField consulting & development Ltd.,

*Add:* Suite 705, 14 Tran Hung Dao, Cotevina Building Hoan Kiem, Hanoi,
Vietnam

*Mobile*: (+84) 986 087 781

*Email*: le.thi.quynh.hoa@gmail.com

**Comment by tylere** [comment]
It it difficult to guess what is going wrong from this limited information.

How are you attempting to run build.sh?
Include the complete error trace, so that others can try to help you resolve it.

**Comment by lequynhhoa** [comment]
I tried to polygon draw example. And the resulting do not display Map.
Could you tell me how to fix it?





Hoa Le

*Le Thi Quynh Hoa*

GreenField consulting & development Ltd.,

*Add:* Suite 705, 14 Tran Hung Dao, Cotevina Building Hoan Kiem, Hanoi,
Vietnam

*Mobile*: (+84) 986 087 781

*Email*: le.thi.quynh.hoa@gmail.com

**Comment by tylere** [comment]
Once again, you will have to provide far more details so that someone can help you debug the issue. Specifically, please details on:

- what you tried
- what behavior you experienced
- any log messages were printed to the terminal window
- any error messages that appear in the browser console

**Comment by lequynhhoa** [comment]
Yes. I download polygon drawing project demo and edit some parameters as
client Id..
When I deploy, the map is not display the Map and draw tool:
https://gfd-forest-196603.appspot.com/


I attached my project here . Could you tell me why don't display map?
Thank you​
 polygon-drawing.zip
<https://drive.google.com/file/d/1gunYIyz0aNHiYaYoxlPIGB-kyS7RbiKb/view?usp=drive_web>
​



Hoa Le

*Le Thi Quynh Hoa*

GreenField consulting & development Ltd.,

*Add:* Suite 705, 14 Tran Hung Dao, Cotevina Building Hoan Kiem, Hanoi,
Vietnam

*Mobile*: (+84) 986 087 781

*Email*: le.thi.quynh.hoa@gmail.com

**Comment by lequynhhoa** [comment]
Hi, tylere

My steps to make app engine server-auth in demos fold earthengine git as below:

1) Authorize access to your Earth Engine account by running via command promt: install earthengine-api and earthengine authenticate (Successfull)

2) Create your own project and download privatekey.json

3) Download earth engine from git hub: git clone https://github.com/google/earthengine-api.git

4) Edit config.py file in server-auth (demos example)

5) Copy privatekey.json into folder including app.yaml

6) Run Build.sh from Google cloud sdk to make folder : ee, httplib2, oauth2client. It's seems some module is not named:
![image](https://user-images.githubusercontent.com/4716948/40706878-431f7700-6419-11e8-9109-941d2e4b3a3c.png)

7) Run dev_appserver.py :I got error
![image](https://user-images.githubusercontent.com/4716948/40706909-59b4031e-6419-11e8-94a4-f677123f90e6.png)

And my folder:
![image](https://user-images.githubusercontent.com/4716948/40706925-63284e5a-6419-11e8-9c7e-325a3cef73a5.png)

**Comment by khegewisch** [comment]
Back to the original issue.... Climate Engine is experiencing this same error sporadically, but with increasing frequency that it is becoming a real problem. 

When loading the page, clim-engine.appspot.com (or app.climateengine.org), the page goes blank with the following error (instead of loading the Climate Engine page)
**Error: Server Error
The server encountered an error and could not complete your request.
Please try again in 30 seconds.**
![Screen Shot 2019-10-17 at 9 15 06 AM](https://user-images.githubusercontent.com/7798273/67029223-c1114680-f0c1-11e9-9c1e-1f28bd345bf2.png)
 
After getting the error, refreshing the page (trying again in 30 sec) sometimes fixes the problem. But sometimes, the server error persists for 5-10 minutes. But then the page is back to normal eventually. We do use the Chrome browser and do a 'hard refresh' to get past Chrome's caching. 

To me, this means that the error can't be due to our code and it can't be due to whitelisting or any permissions errors.  Also, the error does not show up in the error list on the google developer console. So we have no information to troubleshoot this.

It seems that the problem might be related to recent traffic, but this is a total guess.  

Any ideas?

**Comment by tylere** [comment]
Given that ClimateEngine is a custom application, I will reply off-thread to discuss this.

**Comment by tylere** [comment]
In general the "Error: Server Error" message is an App Engine error message. Because App Engine can run arbitrary code it is difficult to speculate on why it is throwing an error.

For more information, there should be log entries for the error in the [Developer Console](https://console.cloud.google.com/). If the log messages are insufficient to determine the cause, you can add additional custom logging messages. See: [Reading and Writing Application Logs](https://cloud.google.com/appengine/docs/standard/python/logs/)

- Tyler

**Comment by tylere** [comment]
We have been transitioning to using Google Issue Tracker for Earth Engine [bug reports](https://issuetracker.google.com/issues?q=componentid:184406%20type:bug) and [feature requests](https://issuetracker.google.com/issues?q=componentid:184406%20type:feature_request) in order to better integrate with the Earth Engine team's workflow.

I am marking this bug as closed, but feel free to open a new bug according to instructions on the Earth Engine doc's [Get Help](https://developers.google.com/earth-engine/help#bug-reports) page.

**Comment by steveschwarz68** [comment]
Script Error 
Git Protocol Error.
Running Google Earth Engine on a Mac (High  Sierra), and when ever trying to save scripts get the error: 
Script error
Git protocol error

****  How do i fix this ?

**Comment by gomalhunzai** [comment]
Hi , i have also encounter the same issue as @steveschwarz68 .But i am working on Windows 10

**Comment by steveschwarz68** [comment]
What I did-
Logged off Google earth engine
Re-booted my desktop
Did not log back in to google engine for 48 hours
Once back in to my Google engine account, deleted files as other users had
mentioned that too many files can cause this problem.
Has worked no problem ever since.
