### ISSUE TITLE
GEE Python client unable to initialize: ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by almetha** [google/earthengine-api#31]
Hi,
I've installed GEE Python API, but I'm unable to initialize it
The message error is:
"ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it". Does anyone know how to solve this issue?

Thanks
Thais.
![error 10061](https://user-images.githubusercontent.com/35684165/35212358-21f6af68-ff5a-11e7-9042-69c283be2c01.jpg)

**Comment by tylere** [comment]
I'll try to help, but this appears to be a [Windows specific error](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681391(v=vs.85).aspx
) and I do not have a Windows machine.

Here is a Stack Overflow questions with potential solutions: [No connection could be made because the target machine actively refused it?](https://stackoverflow.com/questions/2972600/no-connection-could-be-made-because-the-target-machine-actively-refused-it)

If that doesn't help, could you detail exactly how you installed the GEE Python API on your Windows machine, so others with Windows machines can try to replicate the issue?

**Comment by almetha** [comment]
Hi Tyler,
Thanks for your answer,
I forwarded your suggestion to the IT people here at the Institution where I'm working in, and I'll let you know if they can fix this.
**About the installation of the GEE Python API on Windows:**
So, at home, in my personal computer, I had no problems.
I installed Anaconda Navigator (which comes with Jupyter Notebook) and them using the "Command Prompt" from Windows I installed GEE following the suggestion you posted in the "Google Earth Engine Developers" mailing list:
   pip install earthengine-api
   earthengine authenticate
Also, at home, I run your examples from the "ee-jupyter-examples" folder, without any problems.
I tried to do the same here, but it didn't work...
Best regards,
Thais

**Comment by tylere** [comment]
Did your IT group provide any information about what may be causing this?

**Comment by almetha** [comment]
No, they have no idea... I just gave up, and now I'm using my own computer at home and/or my own mobile network :(

**Comment by tylere** [comment]
Understood. Closing this issue, since your IT staff is no longer trying to debug it.

**Comment by jeueblah** [comment]
I have the same issue; I believe it's related to proxy servers. Works at home, not at (proxied) work.

**Comment by jeueblah** [comment]
As a followup, I was able to authenticate by adding proxy handling to the request_token function within the oauth.py file. I inserted the following just before the line `response = urllib.request.urlopen(TOKEN_REQ_RUL...)`:

```
      proxy = urllib.request.ProxyHandler({'http':'proxygoeshere:port','https':'proxygoeshere:port'})
      opener = urllib.request.build_opener(proxy)
      urllib.request.install_opener(opener)

```
