### ISSUE TITLE
Uncaught ReferenceError: google is not defined

### ISSUE THREAD

**Issue by rdgomt** [google/earthengine-api#60]
Hi,

I'm trying to use earthengine-api within a React app, but i'm getting this error (Uncaught ReferenceError: google is not defined) when I run any ee method within a component.

I know it's probably not an issue, but can anyone give me some guide?

**Comment by donmccurdy** [comment]
Hi @rdgomt — could you share more information to help us reproduce the problem? Is earthengine-api installed via NPM, or a script? Which EE methods are you trying to use when seeing the error? A screenshot of the part of the script throwing the error may also be helpful.

**Comment by rdgomt** [comment]
Hi @donmccurdy. It's installed via NPM. In regard to the methods, I'm still in the Hello World...

![code](https://user-images.githubusercontent.com/23437436/46414003-980d5600-c6f8-11e8-9c57-e768168a82f7.png)
![error](https://user-images.githubusercontent.com/23437436/46414004-980d5600-c6f8-11e8-8e7b-71b98f54195c.png)

**Comment by donmccurdy** [comment]
From the [npm installation docs](https://developers.google.com/earth-engine/npm_install):

> Earth Engine APIs use the OAuth 2.0 protocol for authenticating browser-based clients. For server-side authentication in Node.js, service accounts are recommended.

The `googleapis` dependency is not included with the browser package — it's strongly recommended that you use OAuth for client-side JS instead. A private key would otherwise be accessible to all site visitors, who can then perform arbitrary actions in Earth Engine as your account.
