### ISSUE TITLE
earthengine CLI Requests

### ISSUE THREAD

**Issue by PaulMest** [google/earthengine-api#7]
When we were first getting started, it was difficult to figure out permissions and we found a number of machines that were logged in under the wrong account. Having something like this would be helpful in diagnosing permissions problems:
`$ earthengine whoami`
`$ earthengine auth whoami`

I've had some people on my team using an outdated version of the CLI. So have an easy way to determine what version people are running would be helpful.
`$ earthengine version`
`$ earthengine debug version`

**Comment by tylere** [comment]
This feature request has been transitioned to Google Issue Tracker: https://issuetracker.google.com/issues/144848968

In order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for details on how to browse and submit issues to Issue Tracker.
