### ISSUE TITLE
TypeError: Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by erikvaningen** [google/earthengine-api#94]
Javascript:

Version 0.1.180 reports this error while authenticating:
**TypeError: Cannot read property 'querySelector' of undefined**

It does not appear in versions Version 0.1.178 and 0.1.169

**Comment by donmccurdy** [comment]
Thanks – Could you provide more information to help reproduce this? You're running the library in a browser, not a node.js server, I assume? This sounds very similar to https://github.com/google/earthengine-api/issues/92, in which case it should be fixed in the next release, but I'd like to check to confirm.

**Comment by erikvaningen** [comment]
This problems relates to node.js, not to running in a browser. 

See this zip file with a jest test which represents the error. You would need to provide a privatekey.json in a config directory. 
[1_kgz.zip](https://github.com/google/earthengine-api/files/3275115/1_kgz.zip)

Thanks for picking this up!
Best,
Erik

**Comment by donmccurdy** [comment]
Ok thanks! Merging with #92 in that case.
